scss_files: 'app/assets/stylesheets/**'
exclude:
  - 'app/assets/stylesheets/application.css'
  - 'vendor/assets/**'
  - 'app/assets/stylesheets/jquery.mCustomScrollbar.min.css'
  - 'app/assets/stylesheets/magnific-popup.min.css'
  - 'app/assets/stylesheets/theme.min.css'
  - 'app/assets/stylesheets/animate.min.css'
  - 'app/assets/stylesheets/easyzoom.min.css'
  - 'app/assets/stylesheets/flaticon.min.css'
  - 'app/assets/stylesheets/Pe-icon-7-stroke.min.css'
  - 'app/assets/stylesheets/chosen.min.css'
  - 'app/assets/stylesheets/color.min.scss'
  - 'app/assets/stylesheets/admin.css'
  - 'app/assets/stylesheets/admin/metisMenu.min.css'
  - 'app/assets/stylesheets/admin/sb-admin-2.min.css'
